// Cerita bertingkat karya asli THE MARS. Setiap kalimat: [Jepang, terjemahan Indonesia].
// keyVocab: [kata, cara baca, arti Indonesia]. Tambahkan cerita baru dengan format yang sama.
import type { Level } from "../src/lib/types.ts";

export type StorySource = {
  id: string;
  level: Level;
  title: string;
  titleId: string;
  topic: string;
  summary: string;
  sentences: [string, string][];
  keyVocab: [string, string, string][];
};

export const stories: StorySource[] = [
  {
    id: "n5-hari-maya",
    level: 5,
    title: "私の一日",
    titleId: "Satu Hariku",
    topic: "Kehidupan sehari-hari",
    summary: "Maya, pelajar Indonesia di Tokyo, menceritakan rutinitas hariannya.",
    sentences: [
      ["私はマヤです。インドネシア人です。", "Saya Maya. Saya orang Indonesia."],
      ["今、東京に住んでいます。", "Sekarang saya tinggal di Tokyo."],
      ["毎朝、六時に起きます。", "Setiap pagi saya bangun jam enam."],
      ["朝ご飯はパンと卵です。", "Sarapan saya roti dan telur."],
      ["それから、電車で学校へ行きます。", "Setelah itu, saya pergi ke sekolah naik kereta."],
      ["学校で日本語を勉強します。", "Di sekolah saya belajar bahasa Jepang."],
      ["日本語は難しいですが、面白いです。", "Bahasa Jepang sulit, tetapi menarik."],
      ["昼ご飯は友達と食堂で食べます。", "Makan siang saya makan bersama teman di kantin."],
      ["午後三時に家へ帰ります。", "Jam tiga sore saya pulang ke rumah."],
      ["夜は日本のアニメを見ます。", "Malam hari saya menonton anime Jepang."],
      ["アニメで新しい言葉を覚えます。", "Saya menghafal kata-kata baru lewat anime."],
      ["十一時に寝ます。おやすみなさい。", "Saya tidur jam sebelas. Selamat tidur."],
    ],
    keyVocab: [
      ["住む", "すむ", "tinggal"],
      ["起きる", "おきる", "bangun (tidur)"],
      ["電車", "でんしゃ", "kereta listrik"],
      ["勉強", "べんきょう", "belajar"],
      ["難しい", "むずかしい", "sulit"],
      ["面白い", "おもしろい", "menarik, lucu"],
      ["帰る", "かえる", "pulang"],
      ["言葉", "ことば", "kata, bahasa"],
      ["覚える", "おぼえる", "menghafal, mengingat"],
    ],
  },
  {
    id: "n5-belanja",
    level: 5,
    title: "週末の買い物",
    titleId: "Belanja Akhir Pekan",
    topic: "Belanja",
    summary: "Dua kakak-beradik mencari tas di department store dekat stasiun.",
    sentences: [
      ["土曜日、私は妹とデパートへ行きました。", "Hari Sabtu, saya pergi ke department store bersama adik perempuan saya."],
      ["天気はとてもよかったです。", "Cuacanya sangat bagus."],
      ["デパートは駅の前にあります。", "Department store itu ada di depan stasiun."],
      ["妹は赤いかばんが欲しかったです。", "Adik saya ingin tas merah."],
      ["でも、そのかばんは高かったです。", "Tetapi tas itu mahal."],
      ["一万円でした。", "Harganya sepuluh ribu yen."],
      ["妹は「高いですね」と言いました。", "Adik saya berkata, \"Mahal, ya.\""],
      ["それで、私たちは二階の安い店へ行きました。", "Jadi, kami pergi ke toko murah di lantai dua."],
      ["そこに青いかばんがありました。三千円でした。", "Di sana ada tas biru. Harganya tiga ribu yen."],
      ["妹はそのかばんを買いました。", "Adik saya membeli tas itu."],
      ["帰りに、喫茶店でコーヒーを飲みました。", "Dalam perjalanan pulang, kami minum kopi di kafe."],
      ["とても楽しい一日でした。", "Hari itu sangat menyenangkan."],
    ],
    keyVocab: [
      ["妹", "いもうと", "adik perempuan"],
      ["天気", "てんき", "cuaca"],
      ["駅", "えき", "stasiun"],
      ["欲しい", "ほしい", "ingin (memiliki)"],
      ["高い", "たかい", "mahal, tinggi"],
      ["安い", "やすい", "murah"],
      ["買う", "かう", "membeli"],
      ["喫茶店", "きっさてん", "kafe, kedai kopi"],
      ["楽しい", "たのしい", "menyenangkan"],
    ],
  },
  {
    id: "n4-perjalanan-pertama",
    level: 4,
    title: "初めての日本旅行",
    titleId: "Perjalanan Pertama ke Jepang",
    topic: "Wisata",
    summary: "Pengalaman pertama ke Kyoto: sakura, ryokan, onsen, dan keberanian berbicara.",
    sentences: [
      ["去年の春、初めて日本へ旅行に行きました。", "Musim semi tahun lalu, saya pertama kali berwisata ke Jepang."],
      ["空港に着いたとき、少し緊張していました。", "Saat tiba di bandara, saya sedikit gugup."],
      ["駅の人に道を聞いたら、とても親切に教えてくれました。", "Ketika saya bertanya arah kepada petugas stasiun, dia menunjukkannya dengan sangat ramah."],
      ["京都では、古いお寺をたくさん見学しました。", "Di Kyoto, saya mengunjungi banyak kuil tua."],
      ["桜がきれいに咲いていて、写真を何枚も撮りました。", "Sakura mekar dengan indah, dan saya mengambil banyak foto."],
      ["旅館に泊まったので、日本の生活を少し体験することができました。", "Karena menginap di ryokan, saya bisa sedikit merasakan kehidupan Jepang."],
      ["晩ご飯の前に、温泉に入りました。", "Sebelum makan malam, saya berendam di onsen."],
      ["最初は恥ずかしかったですが、すぐに慣れました。", "Awalnya saya malu, tetapi segera terbiasa."],
      ["日本語で話してみると、店の人が喜んでくれました。", "Ketika saya mencoba berbicara dalam bahasa Jepang, penjaga toko terlihat senang."],
      ["言葉が通じたとき、本当にうれしかったです。", "Saat kata-kata saya dimengerti, saya benar-benar senang."],
      ["この旅行のおかげで、もっと日本語を勉強したくなりました。", "Berkat perjalanan ini, saya jadi ingin belajar bahasa Jepang lebih banyak."],
      ["次は北海道へ行ってみたいと思っています。", "Berikutnya, saya ingin mencoba pergi ke Hokkaido."],
    ],
    keyVocab: [
      ["初めて", "はじめて", "pertama kali"],
      ["緊張", "きんちょう", "gugup, tegang"],
      ["親切", "しんせつ", "ramah, baik hati"],
      ["見学", "けんがく", "kunjungan melihat-lihat"],
      ["泊まる", "とまる", "menginap"],
      ["体験", "たいけん", "mengalami langsung"],
      ["慣れる", "なれる", "terbiasa"],
      ["通じる", "つうじる", "dimengerti, tersampaikan"],
    ],
  },
  {
    id: "n4-konbini",
    level: 4,
    title: "コンビニのアルバイト",
    titleId: "Kerja Paruh Waktu di Minimarket",
    topic: "Pekerjaan",
    summary: "Mahasiswa yang belajar keigo dan kesabaran lewat kerja paruh waktu.",
    sentences: [
      ["大学に入ってから、コンビニでアルバイトを始めました。", "Setelah masuk universitas, saya mulai kerja paruh waktu di minimarket."],
      ["週に三回、夕方から夜の十時まで働いています。", "Saya bekerja tiga kali seminggu, dari sore sampai jam sepuluh malam."],
      ["最初は、レジの使い方が分からなくて困りました。", "Awalnya saya kesulitan karena tidak tahu cara memakai mesin kasir."],
      ["でも、店長が何度も丁寧に説明してくれました。", "Tetapi manajer toko menjelaskannya dengan sabar berkali-kali."],
      ["コンビニの仕事は、思ったより大変です。", "Pekerjaan di minimarket lebih berat dari yang saya kira."],
      ["商品を並べたり、掃除をしたり、お弁当を温めたりしなければなりません。", "Saya harus menata barang, membersihkan, menghangatkan bento, dan sebagainya."],
      ["忙しい時間には、お客さんが長い列を作ります。", "Pada jam sibuk, pelanggan membentuk antrean panjang."],
      ["お客さんに「ありがとう」と言われると、疲れていても元気になります。", "Ketika pelanggan berkata \"terima kasih\", saya jadi bersemangat meskipun lelah."],
      ["アルバイトのおかげで、敬語が上手に使えるようになりました。", "Berkat kerja paruh waktu, saya jadi bisa memakai keigo (bahasa hormat) dengan baik."],
      ["来月から、新しい人に仕事を教える予定です。", "Mulai bulan depan, saya dijadwalkan mengajari pekerjaan kepada karyawan baru."],
    ],
    keyVocab: [
      ["働く", "はたらく", "bekerja"],
      ["困る", "こまる", "kesulitan, bingung"],
      ["丁寧", "ていねい", "sopan, teliti"],
      ["説明", "せつめい", "penjelasan"],
      ["大変", "たいへん", "berat, merepotkan"],
      ["並べる", "ならべる", "menata, menjajarkan"],
      ["温める", "あたためる", "menghangatkan"],
      ["敬語", "けいご", "bahasa hormat"],
      ["予定", "よてい", "rencana, jadwal"],
    ],
  },
  {
    id: "n3-bangun-pagi",
    level: 3,
    title: "早起きを始めてみた",
    titleId: "Aku Mencoba Bangun Pagi",
    topic: "Kebiasaan",
    summary: "Seorang \"manusia malam\" mencoba bangun pagi selama sebulan dan menemukan ritmenya.",
    sentences: [
      ["以前の私は、夜遅くまでスマホを見てしまう典型的な夜型人間だった。", "Dulu saya adalah tipe manusia malam yang khas, yang tanpa sadar melihat ponsel sampai larut malam."],
      ["そのせいで、朝はいつも時間に追われ、朝食を抜くことも多かった。", "Karena itu, pagi hari saya selalu dikejar waktu dan sering melewatkan sarapan."],
      ["ある日、友人に勧められて、一か月だけ早起きに挑戦してみることにした。", "Suatu hari, atas saran teman, saya memutuskan mencoba bangun pagi selama sebulan saja."],
      ["最初の一週間は、目覚まし時計が鳴っても、なかなか布団から出られなかった。", "Pada minggu pertama, meskipun jam weker berbunyi, saya susah sekali keluar dari futon."],
      ["そこで、寝る一時間前にはスマホを使わないというルールを作った。", "Lalu saya membuat aturan tidak memakai ponsel satu jam sebelum tidur."],
      ["すると、自然に眠くなり、朝もすっきり起きられるようになった。", "Hasilnya, saya mengantuk secara alami dan bisa bangun pagi dengan segar."],
      ["朝の静かな時間を利用して、日本語のポッドキャストを聞いたり、日記を書いたりしている。", "Saya memanfaatkan waktu pagi yang tenang untuk mendengarkan podcast bahasa Jepang dan menulis buku harian."],
      ["一か月が過ぎた今、早起きは習慣になりつつある。", "Kini, setelah sebulan berlalu, bangun pagi mulai menjadi kebiasaan."],
      ["何より、一日を自分のペースで始められることが一番の変化だと思う。", "Yang terpenting, menurut saya perubahan terbesar adalah bisa memulai hari dengan ritme sendiri."],
      ["生活を変えるのは簡単ではないが、小さなルールから始めれば、意外と続けられるものだ。", "Mengubah gaya hidup memang tidak mudah, tetapi kalau dimulai dari aturan kecil, ternyata bisa dijalani terus."],
    ],
    keyVocab: [
      ["典型的", "てんけいてき", "khas, tipikal"],
      ["抜く", "ぬく", "melewatkan, mencabut"],
      ["勧める", "すすめる", "menyarankan"],
      ["挑戦", "ちょうせん", "tantangan, mencoba"],
      ["利用", "りよう", "memanfaatkan"],
      ["習慣", "しゅうかん", "kebiasaan"],
      ["変化", "へんか", "perubahan"],
      ["意外", "いがい", "di luar dugaan"],
    ],
  },
  {
    id: "n3-toko-roti",
    level: 3,
    title: "商店街の小さなパン屋",
    titleId: "Toko Roti Kecil di Kawasan Pertokoan",
    topic: "Masyarakat",
    summary: "Rahasia toko roti milik seorang kakek yang tetap ramai meski ada supermarket besar.",
    sentences: [
      ["私の家の近くの商店街に、小さなパン屋がある。", "Di kawasan pertokoan dekat rumah saya, ada toko roti kecil."],
      ["店を経営しているのは、七十歳を過ぎたおじいさんだ。", "Yang mengelola toko itu adalah seorang kakek berusia lebih dari tujuh puluh tahun."],
      ["毎朝四時に起きて、一人でパンを焼いているそうだ。", "Katanya, dia bangun jam empat setiap pagi dan memanggang roti sendirian."],
      ["店の前を通ると、いつも焼きたてのパンのいい香りがする。", "Setiap lewat depan toko, selalu tercium aroma harum roti yang baru dipanggang."],
      ["最近、近くに大きなスーパーができて、商店街の客は減ってしまった。", "Belakangan ini, sebuah supermarket besar dibuka di dekat sana, dan pengunjung kawasan pertokoan pun berkurang."],
      ["それでも、このパン屋にだけは毎日のように行列ができる。", "Meski begitu, hanya di toko roti ini antrean terbentuk hampir setiap hari."],
      ["人気の理由を尋ねると、おじいさんは「特別なことは何もしていないよ」と笑った。", "Ketika saya menanyakan alasan kepopulerannya, kakek itu tertawa, \"Saya tidak melakukan hal istimewa apa pun.\""],
      ["ただ、お客さん一人一人の名前と好きなパンを覚えているのだという。", "Hanya saja, katanya dia mengingat nama dan roti kesukaan setiap pelanggan."],
      ["便利さだけでは手に入らない温かさが、人々をこの店に引きつけているのかもしれない。", "Mungkin kehangatan yang tak bisa didapat dari kepraktisan saja itulah yang menarik orang-orang ke toko ini."],
    ],
    keyVocab: [
      ["商店街", "しょうてんがい", "kawasan pertokoan"],
      ["経営", "けいえい", "mengelola usaha"],
      ["焼く", "やく", "memanggang"],
      ["香り", "かおり", "aroma"],
      ["減る", "へる", "berkurang"],
      ["行列", "ぎょうれつ", "antrean"],
      ["尋ねる", "たずねる", "menanyakan"],
      ["引きつける", "ひきつける", "menarik (hati)"],
    ],
  },
  {
    id: "n2-kerja-jarak-jauh",
    level: 2,
    title: "テレワークがもたらしたもの",
    titleId: "Apa yang Dibawa Kerja Jarak Jauh",
    topic: "Masyarakat & pekerjaan",
    summary: "Esai singkat tentang sisi terang dan gelap kerja jarak jauh di Jepang.",
    sentences: [
      ["感染症の流行をきっかけに、多くの企業でテレワークが一気に広まった。", "Dipicu oleh merebaknya wabah, kerja jarak jauh menyebar dengan cepat di banyak perusahaan."],
      ["通勤時間がなくなったことで、家族と過ごす時間が増えたと感じる人は少なくない。", "Tidak sedikit orang yang merasa waktu bersama keluarga bertambah karena tidak perlu lagi menempuh perjalanan ke kantor."],
      ["一方で、仕事と私生活の境目があいまいになり、かえって長時間働いてしまうという声も聞かれる。", "Di sisi lain, ada juga yang mengatakan batas antara pekerjaan dan kehidupan pribadi menjadi kabur, sehingga mereka justru bekerja lebih lama."],
      ["また、同僚と雑談する機会が減ったことで、孤独を感じる社員も増えているという。", "Selain itu, katanya karyawan yang merasa kesepian juga bertambah karena kesempatan mengobrol santai dengan rekan kerja berkurang."],
      ["こうした問題に対応するため、週に数日だけ出社する「ハイブリッド型」の働き方を取り入れる企業が目立っている。", "Untuk menangani masalah seperti ini, semakin banyak perusahaan yang menerapkan cara kerja \"hibrida\", yaitu masuk kantor hanya beberapa hari seminggu."],
      ["対面でのコミュニケーションの価値が、改めて見直されているのである。", "Nilai komunikasi tatap muka kini sedang ditinjau ulang."],
      ["もっとも、どの働き方が最適かは、職種や個人の生活状況によって異なる。", "Namun, cara kerja mana yang paling tepat berbeda-beda tergantung jenis pekerjaan dan situasi hidup masing-masing."],
      ["大切なのは、制度を一律に押し付けるのではなく、働く人が自ら選べる環境を整えることではないだろうか。", "Bukankah yang penting adalah menyiapkan lingkungan agar pekerja bisa memilih sendiri, bukan memaksakan satu sistem untuk semua?"],
    ],
    keyVocab: [
      ["流行", "りゅうこう", "wabah, tren"],
      ["企業", "きぎょう", "perusahaan"],
      ["通勤", "つうきん", "perjalanan ke kantor"],
      ["境目", "さかいめ", "batas"],
      ["孤独", "こどく", "kesepian"],
      ["対応", "たいおう", "menangani, menanggapi"],
      ["取り入れる", "とりいれる", "menerapkan, mengadopsi"],
      ["押し付ける", "おしつける", "memaksakan"],
      ["環境", "かんきょう", "lingkungan"],
    ],
  },
  {
    id: "n2-surat-nenek",
    level: 2,
    title: "祖母の手紙",
    titleId: "Surat-Surat Nenek",
    topic: "Keluarga",
    summary: "Kotak tua berisi surat-surat nenek membuka sisi dirinya yang tak pernah dikenal cucunya.",
    sentences: [
      ["実家の片付けをしていたら、押し入れの奥から古い箱が出てきた。", "Saat membereskan rumah orang tua, sebuah kotak tua muncul dari bagian dalam lemari."],
      ["中には、祖母が若いころに書いた手紙が何十通も大切にしまわれていた。", "Di dalamnya tersimpan rapi puluhan surat yang ditulis nenek semasa muda."],
      ["宛先はすべて、戦後まもなく海外へ働きに出た祖父だった。", "Semuanya ditujukan kepada kakek, yang pergi bekerja ke luar negeri tak lama setelah perang."],
      ["手紙には、日々の出来事や子どもの成長が、丁寧な字でつづられていた。", "Surat-surat itu menuliskan kejadian sehari-hari dan tumbuh kembang anak-anak dengan tulisan tangan yang rapi."],
      ["生活は決して楽ではなかったはずなのに、不満を述べた言葉はほとんど見当たらない。", "Padahal hidupnya pasti sama sekali tidak mudah, tetapi hampir tidak ada kata-kata keluhan."],
      ["むしろ、遠く離れた夫を気遣う言葉ばかりが並んでいた。", "Sebaliknya, yang tertulis hanyalah kata-kata yang mengkhawatirkan suami yang jauh."],
      ["私が知っている祖母は、いつも穏やかで、口数の少ない人だった。", "Nenek yang saya kenal selalu tenang dan tidak banyak bicara."],
      ["その静けさの裏に、これほど深い思いが隠れていたとは、想像もしなかった。", "Saya tak pernah membayangkan bahwa di balik ketenangan itu tersembunyi perasaan sedalam ini."],
      ["メッセージが一瞬で届く時代だからこそ、時間をかけて言葉を選ぶことの重みを感じずにはいられない。", "Justru karena kita hidup di zaman ketika pesan terkirim dalam sekejap, saya tak bisa tidak merasakan beratnya memilih kata dengan meluangkan waktu."],
    ],
    keyVocab: [
      ["実家", "じっか", "rumah orang tua"],
      ["押し入れ", "おしいれ", "lemari dinding"],
      ["宛先", "あてさき", "alamat tujuan"],
      ["成長", "せいちょう", "pertumbuhan"],
      ["不満", "ふまん", "ketidakpuasan, keluhan"],
      ["気遣う", "きづかう", "memperhatikan, mengkhawatirkan"],
      ["穏やか", "おだやか", "tenang, lembut"],
      ["想像", "そうぞう", "membayangkan"],
    ],
  },
  {
    id: "n1-membaca",
    level: 1,
    title: "「読む」という行為の変容",
    titleId: "Perubahan Makna \"Membaca\"",
    topic: "Esai budaya",
    summary: "Esai tentang membaca di layar vs. membaca buku, dan nilai membaca perlahan.",
    sentences: [
      ["スマートフォンの普及に伴い、私たちが一日に目にする文字の量は飛躍的に増大した。", "Seiring meluasnya ponsel pintar, jumlah teks yang kita lihat dalam sehari meningkat drastis."],
      ["にもかかわらず、「本を読まなくなった」と嘆く声は後を絶たない。", "Meski demikian, keluhan bahwa orang \"tidak lagi membaca buku\" tak kunjung berhenti."],
      ["この一見矛盾する現象は、読むという行為そのものの質が変わりつつあることを示唆している。", "Fenomena yang sekilas tampak kontradiktif ini mengisyaratkan bahwa kualitas tindakan membaca itu sendiri sedang berubah."],
      ["画面上の文章は、ともすれば拾い読みされ、要点だけを素早く抽出する対象として扱われがちだ。", "Tulisan di layar cenderung hanya dibaca sekilas dan diperlakukan sebagai bahan untuk mengambil intinya dengan cepat."],
      ["それに対し、紙の本を読む際には、筆者の論理を一歩ずつたどり、行間に込められた意図を汲み取ろうとする姿勢が求められる。", "Sebaliknya, saat membaca buku kertas, dibutuhkan sikap menelusuri logika penulis selangkah demi selangkah dan berusaha menangkap maksud yang tersirat di antara baris."],
      ["もっとも、媒体の違いがそのまま読解の深さを決定づけるわけではない。", "Meskipun begitu, perbedaan media tidak serta-merta menentukan kedalaman pemahaman bacaan."],
      ["問われているのは、情報の洪水の中で、あえて立ち止まり、一つの文章と向き合う時間をいかに確保するかであろう。", "Yang dipertanyakan barangkali adalah bagaimana kita, di tengah banjir informasi, menyisihkan waktu untuk sengaja berhenti dan benar-benar menghadapi satu tulisan."],
      ["速さと効率が重んじられる時代にあってこそ、ゆっくり読むことの意義は一層際立つに違いない。", "Justru di zaman yang mengutamakan kecepatan dan efisiensi, makna membaca perlahan pasti semakin menonjol."],
    ],
    keyVocab: [
      ["普及", "ふきゅう", "penyebaran, meluasnya"],
      ["飛躍的", "ひやくてき", "secara drastis"],
      ["嘆く", "なげく", "mengeluhkan, meratapi"],
      ["示唆", "しさ", "isyarat, mengisyaratkan"],
      ["抽出", "ちゅうしゅつ", "mengekstrak"],
      ["汲み取る", "くみとる", "menangkap (maksud)"],
      ["媒体", "ばいたい", "media, perantara"],
      ["際立つ", "きわだつ", "menonjol"],
    ],
  },
  {
    id: "n1-pengrajin",
    level: 1,
    title: "職人の矜持",
    titleId: "Harga Diri Seorang Pengrajin",
    topic: "Tradisi",
    summary: "Pengrajin pisau generasi ke-15 di Kyoto tentang arti tradisi yang sebenarnya.",
    sentences: [
      ["京都の路地裏に、創業三百年を誇る刃物店がある。", "Di sebuah gang di Kyoto, ada toko pisau yang bangga dengan sejarah tiga ratus tahun."],
      ["十五代目の店主は、機械による大量生産が当たり前となった今もなお、一本一本手作業で包丁を研ぎ上げている。", "Pemilik generasi kelima belas itu, bahkan kini ketika produksi massal dengan mesin sudah lumrah, masih mengasah setiap pisau dengan tangan."],
      ["「効率だけを追い求めていたら、とうの昔に店を畳んでいたでしょう」と彼は淡々と語る。", "\"Kalau hanya mengejar efisiensi, toko ini pasti sudah lama tutup,\" katanya dengan tenang."],
      ["注文から完成までに半年を要することも珍しくないが、国内外から依頼が絶えることはない。", "Tidak jarang butuh setengah tahun dari pemesanan sampai selesai, tetapi permintaan dari dalam dan luar negeri tak pernah berhenti."],
      ["彼が何より重んじているのは、使い手の癖や用途を見極めたうえで、その人だけの一本を仕上げることだという。", "Katanya, yang paling ia utamakan adalah membuat satu pisau khusus untuk orang itu, setelah benar-benar memahami kebiasaan dan kebutuhan si pemakai."],
      ["後継者不足が叫ばれて久しいが、近年は彼のもとで修業を志願する若者も現れ始めた。", "Kekurangan penerus sudah lama dikeluhkan, namun belakangan mulai muncul anak muda yang ingin berguru kepadanya."],
      ["伝統とは、形を守ることではなく、精神を受け継ぐことにほかならない——その言葉には、長年刃物と向き合ってきた者ならではの重みがあった。", "Tradisi bukanlah menjaga bentuk, melainkan tak lain adalah mewarisi semangat — kata-kata itu memiliki bobot yang hanya dimiliki orang yang bertahun-tahun menekuni pisau."],
    ],
    keyVocab: [
      ["路地裏", "ろじうら", "gang belakang"],
      ["創業", "そうぎょう", "pendirian usaha"],
      ["研ぐ", "とぐ", "mengasah"],
      ["淡々", "たんたん", "tenang, datar"],
      ["要する", "ようする", "membutuhkan"],
      ["見極める", "みきわめる", "memahami dengan saksama"],
      ["後継者", "こうけいしゃ", "penerus"],
      ["受け継ぐ", "うけつぐ", "mewarisi"],
    ],
  },
  {
    id: "n5-keluarga",
    level: 5,
    title: "私の家族",
    titleId: "Keluargaku",
    topic: "Keluarga",
    summary: "Perkenalan anggota keluarga dan kegiatan hari Minggu bersama.",
    sentences: [
      ["私の家族は五人です。", "Keluarga saya ada lima orang."],
      ["父と母と兄と妹と私です。", "Ayah, ibu, kakak laki-laki, adik perempuan, dan saya."],
      ["父は会社員です。毎日、朝早く会社へ行きます。", "Ayah saya karyawan kantor. Setiap hari dia berangkat ke kantor pagi-pagi."],
      ["母は料理がとても上手です。", "Ibu saya sangat pandai memasak."],
      ["母のカレーは世界で一番おいしいです。", "Kari buatan ibu adalah yang paling enak di dunia."],
      ["兄は大学生で、サッカーが好きです。", "Kakak laki-laki saya mahasiswa, dan dia suka sepak bola."],
      ["妹はまだ小学生です。よく歌を歌います。", "Adik perempuan saya masih SD. Dia sering bernyanyi."],
      ["日曜日は、みんなで公園へ行きます。", "Hari Minggu kami semua pergi ke taman."],
      ["公園でお弁当を食べます。", "Kami makan bekal di taman."],
      ["私は家族が大好きです。", "Saya sangat sayang keluarga saya."],
    ],
    keyVocab: [
      ["家族", "かぞく", "keluarga"],
      ["父", "ちち", "ayah (sendiri)"],
      ["母", "はは", "ibu (sendiri)"],
      ["兄", "あに", "kakak laki-laki"],
      ["会社員", "かいしゃいん", "karyawan kantor"],
      ["料理", "りょうり", "masakan, memasak"],
      ["上手", "じょうず", "pandai, mahir"],
      ["公園", "こうえん", "taman"],
      ["大好き", "だいすき", "sangat suka"],
    ],
  },
  {
    id: "n4-hari-hujan",
    level: 4,
    title: "雨の日の出会い",
    titleId: "Pertemuan di Hari Hujan",
    topic: "Pertemanan",
    summary: "Hujan mendadak membawa pertemuan dengan teman belajar bahasa.",
    sentences: [
      ["先週の金曜日、仕事の帰りに急に雨が降り出しました。", "Jumat lalu, dalam perjalanan pulang kerja, tiba-tiba turun hujan."],
      ["傘を持っていなかったので、駅の近くの本屋に入りました。", "Karena tidak membawa payung, saya masuk ke toko buku dekat stasiun."],
      ["雨がやむまで、日本語の本を読むことにしました。", "Saya memutuskan membaca buku bahasa Jepang sampai hujan reda."],
      ["すると、隣にいた女の人が「その本、面白いですよ」と話しかけてくれました。", "Lalu, perempuan di sebelah saya menyapa, \"Buku itu menarik, lho.\""],
      ["彼女は近くの高校で英語を教えている先生でした。", "Ternyata dia guru bahasa Inggris di SMA dekat sana."],
      ["私が日本語を勉強していると言うと、とても喜んでくれました。", "Ketika saya bilang sedang belajar bahasa Jepang, dia terlihat sangat senang."],
      ["三十分ぐらい話していたら、いつの間にか雨はやんでいました。", "Setelah mengobrol sekitar tiga puluh menit, tanpa terasa hujan sudah reda."],
      ["別れる前に、連絡先を交換しました。", "Sebelum berpisah, kami bertukar kontak."],
      ["今では、毎週一回、日本語と英語を教え合っています。", "Sekarang kami saling mengajarkan bahasa Jepang dan Inggris seminggu sekali."],
      ["雨の日も、たまには悪くないと思いました。", "Saya jadi berpikir, hari hujan sesekali tidak buruk juga."],
    ],
    keyVocab: [
      ["急に", "きゅうに", "tiba-tiba"],
      ["降り出す", "ふりだす", "mulai turun (hujan)"],
      ["やむ", "やむ", "reda, berhenti"],
      ["話しかける", "はなしかける", "menyapa, mengajak bicara"],
      ["喜ぶ", "よろこぶ", "senang, gembira"],
      ["いつの間にか", "いつのまにか", "tanpa terasa"],
      ["連絡先", "れんらくさき", "kontak"],
      ["交換", "こうかん", "bertukar"],
    ],
  },
  {
    id: "n3-pilah-sampah",
    level: 3,
    title: "ゴミの分別に苦労した話",
    titleId: "Susahnya Memilah Sampah",
    topic: "Kehidupan di Jepang",
    summary: "Salah hari buang sampah justru membuka pertemanan dengan tetangga.",
    sentences: [
      ["日本に引っ越してきて、最初に驚いたのはゴミの分別の細かさだった。", "Setelah pindah ke Jepang, hal pertama yang mengejutkan saya adalah betapa rincinya pemilahan sampah."],
      ["燃えるゴミ、燃えないゴミ、資源ゴミなど、種類ごとに出す曜日が決まっている。", "Sampah yang bisa dibakar, tidak bisa dibakar, sampah daur ulang, dan lainnya, masing-masing punya hari pembuangan sendiri."],
      ["しかも、ペットボトルはラベルとキャップを外してから捨てなければならない。", "Lebih dari itu, botol plastik harus dilepas label dan tutupnya sebelum dibuang."],
      ["ある朝、間違った日にゴミを出してしまい、近所のおばあさんに注意された。", "Suatu pagi, saya terlanjur membuang sampah di hari yang salah dan ditegur oleh nenek tetangga."],
      ["恥ずかしくて謝ると、おばあさんは怒らずに、分別の方法を丁寧に教えてくれた。", "Saya malu dan meminta maaf. Nenek itu tidak marah, malah mengajari cara memilah dengan teliti."],
      ["さらに、市役所で配っているゴミの出し方のカレンダーまでくれた。", "Dia bahkan memberi saya kalender jadwal buang sampah yang dibagikan balai kota."],
      ["それ以来、カレンダーを冷蔵庫に貼って、毎日確認するようにしている。", "Sejak itu, saya menempel kalender di kulkas dan membiasakan diri mengeceknya setiap hari."],
      ["面倒だと思っていた分別も、慣れてしまえば難しくない。", "Pemilahan yang dulu terasa merepotkan, setelah terbiasa ternyata tidak sulit."],
      ["何より、この出来事のおかげで近所の人と話すきっかけができたのがうれしかった。", "Yang paling menyenangkan, berkat kejadian ini saya punya alasan untuk mengobrol dengan tetangga."],
    ],
    keyVocab: [
      ["引っ越す", "ひっこす", "pindah rumah"],
      ["分別", "ぶんべつ", "pemilahan (sampah)"],
      ["資源", "しげん", "sumber daya, bahan daur ulang"],
      ["外す", "はずす", "melepas"],
      ["注意", "ちゅうい", "teguran, peringatan"],
      ["謝る", "あやまる", "meminta maaf"],
      ["市役所", "しやくしょ", "balai kota"],
      ["面倒", "めんどう", "merepotkan"],
    ],
  },
  {
    id: "n2-kurang-tidur",
    level: 2,
    title: "睡眠不足の国",
    titleId: "Negeri yang Kurang Tidur",
    topic: "Kesehatan & masyarakat",
    summary: "Esai tentang budaya kurang tidur di Jepang dan cara pandang baru terhadap tidur.",
    sentences: [
      ["日本人の平均睡眠時間は、先進国の中でも特に短いと言われている。", "Rata-rata jam tidur orang Jepang dikatakan termasuk yang paling pendek di antara negara maju."],
      ["長時間労働や通勤時間の長さに加え、夜遅くまでスマートフォンを手放せない生活習慣も、その原因の一つとされる。", "Selain jam kerja yang panjang dan lamanya perjalanan ke kantor, kebiasaan tidak bisa lepas dari ponsel sampai larut malam juga dianggap salah satu penyebabnya."],
      ["睡眠不足が続くと、集中力や判断力が低下するだけでなく、心身の健康にも深刻な影響を及ぼしかねない。", "Jika kurang tidur terus berlanjut, bukan hanya konsentrasi dan daya pertimbangan yang menurun, tetapi juga bisa berdampak serius pada kesehatan fisik dan mental."],
      ["実際、睡眠不足による経済的損失は、年間で数兆円に上るという試算もある。", "Faktanya, ada perkiraan bahwa kerugian ekonomi akibat kurang tidur mencapai beberapa triliun yen per tahun."],
      ["こうした状況を受けて、社員の睡眠を支援する取り組みを始める企業も出てきた。", "Menanggapi situasi ini, mulai muncul perusahaan yang berupaya mendukung tidur karyawannya."],
      ["昼休みに短い仮眠を認めたり、深夜のメール送信を禁止したりする例がその代表だ。", "Contoh utamanya adalah mengizinkan tidur singkat saat istirahat siang dan melarang pengiriman email larut malam."],
      ["とはいえ、会社の制度だけで問題が解決するわけではない。", "Meski begitu, masalah ini tidak serta-merta selesai hanya dengan aturan perusahaan."],
      ["眠ることを「時間の無駄」ではなく「明日への投資」と捉え直す意識の変化こそが、今求められているのではないだろうか。", "Bukankah yang justru dibutuhkan sekarang adalah perubahan cara pandang: melihat tidur bukan sebagai \"buang waktu\", melainkan \"investasi untuk hari esok\"?"],
    ],
    keyVocab: [
      ["平均", "へいきん", "rata-rata"],
      ["先進国", "せんしんこく", "negara maju"],
      ["手放す", "てばなす", "melepaskan"],
      ["低下", "ていか", "penurunan"],
      ["及ぼす", "およぼす", "menimbulkan (dampak)"],
      ["損失", "そんしつ", "kerugian"],
      ["仮眠", "かみん", "tidur singkat"],
      ["捉え直す", "とらえなおす", "memandang ulang"],
    ],
  },
  {
    id: "n1-membaca-suasana",
    level: 1,
    title: "「空気を読む」ことの功罪",
    titleId: "Untung-Rugi \"Membaca Suasana\"",
    topic: "Esai budaya",
    summary: "Kapan kebiasaan membaca suasana menjadi kebijaksanaan, dan kapan menjadi tekanan.",
    sentences: [
      ["日本社会において「空気を読む」能力は、円滑な人間関係を築く上で欠かせないものとされてきた。", "Dalam masyarakat Jepang, kemampuan \"membaca suasana\" selama ini dianggap mutlak diperlukan untuk membangun hubungan antarmanusia yang lancar."],
      ["言葉にされない相手の意図を察し、場の雰囲気に合わせて振る舞うことは、確かに摩擦を最小限に抑える知恵と言えよう。", "Menangkap maksud lawan bicara yang tak terucap dan bertindak sesuai suasana memang bisa disebut kebijaksanaan untuk menekan gesekan seminimal mungkin."],
      ["しかしながら、その同調圧力が行き過ぎれば、異なる意見を口にすることさえためらわれる息苦しい空間を生み出しかねない。", "Namun, bila tekanan untuk menyesuaikan diri itu berlebihan, ia bisa menciptakan ruang yang menyesakkan, tempat orang bahkan ragu menyuarakan pendapat yang berbeda."],
      ["会議で誰もが疑問を抱きながら沈黙を守り、結果として誤った決定が下されるという事態は、決して珍しくない。", "Situasi ketika semua orang dalam rapat menyimpan keraguan namun tetap diam, sehingga akhirnya keputusan yang keliru diambil, sama sekali tidak jarang."],
      ["多様な価値観を持つ人々が共に働く時代にあって、暗黙の了解に頼るコミュニケーションには限界がある。", "Di zaman ketika orang-orang dengan beragam nilai bekerja bersama, komunikasi yang bergantung pada pemahaman tersirat memiliki batas."],
      ["もっとも、空気を読むこと自体を否定するには及ばない。", "Meski demikian, kita tidak perlu sampai menolak kebiasaan membaca suasana itu sendiri."],
      ["肝心なのは、空気を読んだうえで、あえて「空気を変える」一言を発する勇気を持てるかどうかであろう。", "Yang terpenting barangkali adalah apakah kita punya keberanian untuk sengaja mengucapkan satu kalimat yang \"mengubah suasana\", setelah membaca suasana itu."],
    ],
    keyVocab: [
      ["円滑", "えんかつ", "lancar"],
      ["欠かせない", "かかせない", "mutlak diperlukan"],
      ["察する", "さっする", "menangkap (maksud tersirat)"],
      ["摩擦", "まさつ", "gesekan"],
      ["同調圧力", "どうちょうあつりょく", "tekanan untuk menyesuaikan diri"],
      ["沈黙", "ちんもく", "diam, kebisuan"],
      ["暗黙の了解", "あんもくのりょうかい", "pemahaman tersirat"],
      ["肝心", "かんじん", "yang terpenting"],
    ],
  },
];
